version: '3.8'

services:
  credit-scoring-api:
    build: .
    container_name: bati_bank_scoring_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production